/*
 * EverythinInAI — Terms of Service
 * Plain-language ToS page; B15 backstop for legal links.
 */

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="max-w-3xl mx-auto px-4 sm:px-6 pt-32 pb-16">
        <h1 className="text-3xl sm:text-4xl font-semibold tracking-tight text-foreground mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: May 9, 2026</p>

        <section className="prose prose-sm max-w-none text-foreground space-y-6">
          <div>
            <h2 className="text-xl font-semibold mb-2">Use of the site</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              EverythinInAI is a free directory of AI tools. You may browse, search,
              and click through to the original tools at no cost. Bots and automated
              scrapers must respect a polite rate limit and identify themselves via
              User-Agent.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">No warranty on listed tools</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We curate metadata about third-party AI tools but do not own, operate,
              endorse, or guarantee any of them. Pros, cons, and pricing labels are
              best-effort summaries generated by our enrichment pipeline. Always
              verify on the tool's own website before trusting your data to it.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">User-submitted content</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              If you submit a tool for inclusion (via email or the Launchpad form), you
              warrant that you have rights to do so and grant us a non-exclusive
              license to display the metadata you provide. We may decline submissions
              at our sole discretion.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">Liability</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              The site is provided "as is." We are not liable for indirect, incidental,
              or consequential damages arising from your use of any tool you found via
              this directory. Our maximum liability for any claim is limited to USD 50.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">Changes</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We may update these terms occasionally. Material changes will be noted
              at the top of this page. Continued use after changes constitutes
              acceptance.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">Contact</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Questions? <a className="underline" href="mailto:hello@everythininai.com">hello@everythininai.com</a>
            </p>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
