-- ═══════════════════════════════════════════════════════════════════════════════
-- EverythinInAI — Voice Schema
--
-- Stores the reference voice clip used to clone Avi's voice,
-- plus per-Reel TTS audio tracks generated by Chatterbox.
-- ═══════════════════════════════════════════════════════════════════════════════

-- Add voice reference URL to personas table for fast lookup
ALTER TABLE personas
    ADD COLUMN IF NOT EXISTS active_voice_ref_url TEXT,
    ADD COLUMN IF NOT EXISTS active_voice_settings JSONB DEFAULT '{}';

-- ═══════════════════════════════════════════════════════════════════════════════
-- Voice clones — multiple references can be tested per persona, one is active
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS persona_voice_refs (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    persona_id      UUID NOT NULL REFERENCES personas(id) ON DELETE CASCADE,

    -- Source
    source_label    TEXT NOT NULL,              -- 'mostly_sane_youtube', 'kusha_kapila_pod', etc.
    source_url      TEXT,                       -- where the clip came from (attribution)
    audio_url       TEXT NOT NULL,              -- public Supabase Storage URL of the clip
    storage_path    TEXT NOT NULL,
    duration_sec    NUMERIC(6, 2),

    -- Test sample (optional — generated by chatterbox using this ref + a stock prompt)
    test_sample_url TEXT,
    test_sample_text TEXT,

    -- Settings (chatterbox params used at activation)
    settings        JSONB DEFAULT '{"cfg_weight": 0.5, "temperature": 0.8, "exaggeration": 0.5}',

    is_active       BOOLEAN DEFAULT FALSE,
    activated_at    TIMESTAMPTZ,
    notes           TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_voice_refs_persona ON persona_voice_refs (persona_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_voice_refs_one_active
    ON persona_voice_refs (persona_id) WHERE is_active = TRUE;

ALTER TABLE persona_voice_refs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS persona_voice_refs_public_read ON persona_voice_refs;
CREATE POLICY persona_voice_refs_public_read ON persona_voice_refs FOR SELECT USING (TRUE);

-- ═══════════════════════════════════════════════════════════════════════════════
-- Per-Reel voice track table (one MP3 per concept)
-- ═══════════════════════════════════════════════════════════════════════════════

ALTER TABLE reel_concepts
    ADD COLUMN IF NOT EXISTS voice_storage_path TEXT,
    ADD COLUMN IF NOT EXISTS voice_duration_sec NUMERIC(6, 2),
    ADD COLUMN IF NOT EXISTS voice_cost_usd NUMERIC(10, 4),
    ADD COLUMN IF NOT EXISTS voice_model TEXT;

SELECT 'voice schema applied' AS status,
       (SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'persona_voice_refs') AS exists;
