-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 015: content_frameworks (the dynamic framework registry)
-- ═══════════════════════════════════════════════════════════════════════════
-- Stores all content frameworks for the 3 streams (tech, lure, lifestyle).
-- The framework_evolution.js cron mutates this table monthly:
--   - disables losers (retention < 15% over 3+ tests)
--   - inserts new frameworks generated by Gemini based on winners
--
-- Keeping frameworks in the DB (not hardcoded) means we can evolve content
-- strategy forever without touching code.

CREATE TABLE IF NOT EXISTS content_frameworks (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug            text UNIQUE NOT NULL,            -- e.g. 'secret_weapon', 'mirror_selfie_classy'
  stream          text NOT NULL,                   -- 'tech' | 'lure' | 'lifestyle'
  display_name    text NOT NULL,                   -- human-readable name
  description     text NOT NULL,                   -- one-line description
  prompt_template text NOT NULL,                   -- detailed instructions injected into Gemini
  example_hook    text,                            -- example output for the LLM to mimic
  is_active       boolean NOT NULL DEFAULT true,   -- killed frameworks are kept for history but not used
  generation      integer NOT NULL DEFAULT 1,      -- which evolution generation this came from
  parent_slug     text,                            -- if it was bred from a winner, what's the parent
  reasoning       text,                            -- why the LLM thought this would work
  created_at      timestamptz NOT NULL DEFAULT now(),
  retired_at      timestamptz,
  retired_reason  text
);

CREATE INDEX IF NOT EXISTS idx_content_frameworks_stream ON content_frameworks(stream) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_content_frameworks_active ON content_frameworks(is_active);

-- ═════════════════════════════════════════
-- Seed: Initial frameworks for all 3 streams
-- ═════════════════════════════════════════

-- TECH STREAM (Mon-Thu)
INSERT INTO content_frameworks (slug, stream, display_name, description, prompt_template, example_hook, generation, reasoning) VALUES
  ('secret_weapon', 'tech', 'Secret Weapon',
   'Saves-driven: positions the AI tool as a money/time-saving secret',
   'Frame the AI tool as a "secret weapon" that replaces an expensive incumbent. Hook starts with "Stop paying for [X]." Body explains the cheaper/free alternative. Punch creates FOMO.',
   'Stop paying for ChatGPT Plus. This open-source model just beat it.',
   1, 'Initial framework - Saves are the strongest IG algo signal'),

  ('industry_killer', 'tech', 'Industry Killer',
   'Shares-driven: triggers fear/urgency about job/industry disruption',
   'Frame the AI as a direct threat to a specific profession. Hook addresses the profession by name. Body explains the threat with specifics. Punch leaves them questioning their career.',
   'If you are a copywriter, this new AI just took your job.',
   1, 'Initial framework - Fear triggers shares with peers'),

  ('i_tested_it', 'tech', 'I Tested It',
   'Watch-time-driven: builds authority through firsthand experimentation',
   'Position Rhea as having personally tested the tool. Hook references the hype. Body shares the "real" result vs the claim. Punch is a hot take on whether it lives up.',
   'Everyone is hyping Sora 2. I actually tested it. Here is the truth.',
   1, 'Initial framework - "I tested" drives full watch-through'),

  ('contrarian_truth', 'tech', 'Contrarian Truth',
   'Comments-driven: takes a controversial stance vs popular opinion',
   'Take a contrarian position on a popular tool/opinion. Hook breaks consensus. Body explains the unconventional view. Punch invites debate without being clickbaity.',
   'Everyone is using Cursor wrong. Here is what actually works.',
   1, 'Initial framework - Controversy drives comments'),

  ('seamless_loop', 'tech', 'Seamless Loop',
   'Rewatch-driven: ends with sentence that flows back to start',
   'Engineer the script so the last sentence flows grammatically into the first. The viewer rewatches without realizing. Hook and punch must form a loop.',
   '...and that is exactly why → ChatGPT will be obsolete by next year.',
   1, 'Initial framework - Loops boost rewatch rate which Instagram weights heavily');

-- LURE STREAM (Friday) - photo posts, slice-of-life, desirable, classy
INSERT INTO content_frameworks (slug, stream, display_name, description, prompt_template, example_hook, generation, reasoning) VALUES
  ('mirror_selfie_classy', 'lure', 'Mirror Selfie',
   'Casual mirror selfie capturing an "unfiltered" moment',
   'Generate a Lure photo concept where Rhea takes a casual mirror selfie. Phone partially covering face. Setting: chic bathroom or walk-in closet. Outfit: elegant evening dress or expensive lounge set. Lighting: warm vanity light. Vibe: effortless, looking incredible without trying.',
   'Mirror selfie before dinner', 1, 'Mirror selfies feel natural and parasocial - unfiltered intimacy'),

  ('cafe_candid', 'lure', 'Cafe Candid',
   'Aesthetic cafe shot, candid laugh or thoughtful sip',
   'Generate a Lure photo concept where Rhea is sitting in an aesthetic high-end cafe. Captured mid-laugh or mid-sip. Natural sunlight. Outfit: oversized linen shirt over fitted camisole, weekend chic. Vibe: she has somewhere to be but is enjoying this moment.',
   'Saturday morning in Bandra', 1, 'Cafe shots project lifestyle wealth and casual sophistication'),

  ('golden_hour_balcony', 'lure', 'Golden Hour Balcony',
   'Apartment balcony at golden hour with city skyline',
   'Generate a Lure photo concept where Rhea is leaning on her apartment balcony railing at golden hour. Mumbai/Bandra skyline in soft bokeh. Looking back over shoulder with mysterious half-smile. Outfit: silk slip or fitted high-neck top. Lighting: warm tungsten + golden sun.',
   'Tonight feels different', 1, 'Golden hour + skyline = aspirational, romantic'),

  ('dressed_up_elevator', 'lure', 'Dressed Up Elevator',
   'Full glam outfit in an elevator mirror',
   'Generate a Lure photo concept where Rhea is dressed up for an event, capturing herself in a sleek elevator mirror. Outfit: full evening gown or designer dress. Vibe: she is going somewhere expensive. Hair and makeup are flawless. Caption hints at the night ahead without specifying.',
   'Going where, none of your business', 1, 'Glam shots create desire and mystery'),

  ('morning_kitchen', 'lure', 'Morning Kitchen',
   'Bright modern kitchen, "I woke up like this" energy',
   'Generate a Lure photo concept where Rhea is in a bright modern kitchen holding a matcha latte. Looking directly at camera with fresh-faced natural smile. Outfit: cozy high-end matching lounge set. Hair in messy bun with face-framing pieces. Vibe: rich morning routine.',
   'My morning routine fixed me', 1, 'Soft morning light + lifestyle wealth = aspirational + relatable'),

  ('vacation_stroll', 'lure', 'Vacation Stroll',
   'Walking down a European cobblestone street at dusk',
   'Generate a Lure photo concept where Rhea is walking down a European-style cobblestone street at dusk. Looking back over shoulder with inviting smile. Fairy lights in background. Outfit: chic summer evening, off-shoulder top + flowing skirt. Vibe: travel envy.',
   'I should travel more', 1, 'Vacation content triggers escapism and envy');

-- LIFESTYLE STREAM (Sat-Sun) - video posts, action, jealousy, aspirational
INSERT INTO content_frameworks (slug, stream, display_name, description, prompt_template, example_hook, generation, reasoning) VALUES
  ('gym_workout', 'lifestyle', 'Gym Workout',
   'Mid-action lifting at a luxury gym, athletic confidence',
   'Generate a Lifestyle video concept where Rhea is performing a controlled athletic movement (kettlebell swing, deadlift, shoulder press) in a high-end modern gym. Floor-to-ceiling windows, morning sun. Outfit: sleek matching black athletic set. Music: upbeat motivational. Caption hints at her discipline.',
   'No excuses', 1, 'Fitness content projects self-discipline and high-status body'),

  ('pilates_studio', 'lifestyle', 'Pilates Studio',
   'Graceful reformer pilates flow in pristine studio',
   'Generate a Lifestyle video concept where Rhea performs a slow controlled pilates reformer movement in a bright studio. Outfit: minimalist matching beige pilates set. Music: calm ambient. Vibe: composed, intentional, expensive hobby.',
   'How I stay grounded', 1, 'Pilates is shorthand for "wealthy enough to afford this lifestyle"'),

  ('luxury_drive', 'lifestyle', 'Luxury Drive',
   'Driving a luxury car at golden hour',
   'Generate a Lifestyle video concept where Rhea is driving a luxury car (matte black or white sports coupe) at golden hour. Hair flowing in breeze from open window. Outfit: oversized linen shirt, designer aviators. Music: upbeat cinematic. Vibe: she goes wherever she wants.',
   'Sunset drives hit different', 1, 'Driving content = freedom + wealth signal'),

  ('penthouse_swim', 'lifestyle', 'Penthouse Swim',
   'Emerging from infinity pool with mountain/city view',
   'Generate a Lifestyle video concept where Rhea is emerging from a luxury infinity pool at golden hour. Water glistening, hair slicked back wet. Slow motion droplet shot. Mountain or ocean view in background. Outfit: classy modest one-piece in deep emerald or black. Music: dreamy ambient.',
   'Pool day', 1, 'Pool content = vacation aspiration + body confidence (without being thirst-trap)'),

  ('mountain_hike', 'lifestyle', 'Mountain Hike',
   'Confident hiking with sweeping mountain vista',
   'Generate a Lifestyle video concept where Rhea is hiking on a scenic mountain trail with sweeping valley views behind. Mid-stride with hiking pole. Confident smile looking at vista. Outfit: technical hiking gear, fitted thermals + jacket. Music: epic cinematic. Vibe: adventure.',
   'I needed this', 1, 'Adventure content = depth + range, attractive to discerning audience'),

  ('cozy_sunday_dance', 'lifestyle', 'Cozy Sunday Dance',
   'Twirling playfully in a minimalist apartment',
   'Generate a Lifestyle video concept where Rhea is twirling and dancing playfully in a beautiful minimalist apartment. Captured mid-laugh, hair flowing dynamically. Warm evening light. Outfit: flowing silk slip dress, bare feet. Music: upbeat indie pop. Vibe: pure unfiltered joy.',
   'Sunday self-care', 1, 'Joyful candid content makes the audience parasocially fall in love');
