-- ═══════════════════════════════════════════════════════════════════════════════
-- Migration 028: Lure Framework Overhaul — concrete garments, color rotation,
-- mandatory full-body framing, standing poses (no seated cut-offs).
--
-- Why: Renders kept producing (a) wrong outfit (knit bralette instead of silk
-- blouse), (b) same cream/beige color palette every time, (c) chest-up framing
-- because seated frameworks cut the body off at hip level.
--
-- Fix: Each prompt_template now specifies:
--   - EXACT garment construction ("fully buttoned silk blouse, all 6 buttons
--     done, top button at the throat") so Flux can't substitute a bralette.
--   - DIVERSE color palettes per framework so we don't keep getting cream.
--   - STANDING or LEANING pose with body fully in frame (no seated tables).
--   - Mandatory "full-body shot from head to mid-shin, body silhouette and
--     entire outfit clearly visible".
-- ═══════════════════════════════════════════════════════════════════════════════

-- 1. Update existing 12 lure frameworks with hardened prompt_templates
UPDATE content_frameworks SET prompt_template = $$Generate a Lure photo concept where Rhea is standing confidently in front of a large vintage-gold-framed mirror in a chic walk-in closet, holding her phone at chest height to take the mirror selfie, slight forward lean toward the mirror with a magnetic closed smile, full-body framing showing her entire outfit head to mid-shin clearly. Outfit MUST be a fully-fitted floor-length silk slip dress in MIDNIGHT BLACK with thin spaghetti straps and a tasteful cowl neckline that stops AT the collarbone (no cleavage spillage), the slip dress hugs her hourglass figure showing defined waist and curves clearly visible through the fabric. Hair loose and wavy. Soft warm tungsten light from a vanity bulb at the side. Vibe: glam, magnetic, going-out energy, the kind of mirror selfie that screams "expensive evening".$$
WHERE slug = 'mirror_selfie_classy';

UPDATE content_frameworks SET prompt_template = $$Generate a Lure photo concept where Rhea is standing in an aesthetic high-end Bandra cafe holding a matcha latte in both hands at chest height, mid-laugh with her head tilted slightly back, natural sunlight through floor-to-ceiling windows behind her, full-body framing showing her entire outfit head to mid-shin. Outfit MUST be a fitted high-waisted denim midi skirt in DEEP INDIGO BLUE paired with an oversized crisp white linen button-down shirt with the top 3 buttons left open showing collarbone (NOT cleavage), the shirt hem tucked in to show her defined waist, sleeves rolled to elbows, with a thin braided leather belt. Sleek leather sandals visible. Hair loose with face-framing pieces. Vibe: weekend chic, intelligent, casually expensive.$$
WHERE slug = 'cafe_candid';

UPDATE content_frameworks SET prompt_template = $$Generate a Lure photo concept where Rhea is leaning casually against her Bandra apartment balcony railing at golden hour with the soft-focus Mumbai skyline behind her, looking back over her shoulder with a warm magnetic smile, full-body framing showing her entire outfit head to mid-shin. Outfit MUST be a fitted floor-length wrap dress in DEEP EMERALD GREEN satin with long flowing sleeves and a high boat-neck collar (no cleavage, no V-neck), the wrap dress accentuates her hourglass silhouette, defined waist tied with the dress's matching satin sash, the skirt hem flowing gently around her ankles. Gold strappy heeled sandals. Hair in soft waves cascading down her back. Vibe: aspirational, romantic, magazine-cover quality.$$
WHERE slug = 'golden_hour_balcony';

UPDATE content_frameworks SET prompt_template = $$Generate a Lure photo concept where Rhea is standing inside a sleek mirrored elevator capturing herself in the reflection, one hand resting on the brass handrail, body angled three-quarter to the mirror with a knowing smirk, full-body framing showing her entire outfit head to floor including the elevator floor reflection. Outfit MUST be a structured fitted bodycon midi dress in BURGUNDY WINE-RED with cap sleeves, a high crew neckline (NO V-neck, NO cleavage, fabric covers the entire chest from collarbone down), and a hem that stops at mid-calf, paired with strappy black leather stiletto heels. Hair pulled back into a sleek low chignon with face-framing strands loose. Diamond stud earrings. Vibe: she is going somewhere expensive, late-evening glam, mystery.$$
WHERE slug = 'dressed_up_elevator';

UPDATE content_frameworks SET prompt_template = $$Generate a Lure photo concept where Rhea is standing barefoot on the smooth wooden floor of a bright modern kitchen, leaning against the marble island with both elbows resting on the counter, holding a large ceramic mug of matcha latte at chest height, looking directly at the camera with a fresh-faced natural smile, full-body framing showing her entire outfit head to mid-shin. Outfit MUST be a soft loose ribbed-knit lounge set in DUSTY ROSE PINK with a long-sleeve cropped sweater that ends AT her natural waistline (no exposed midriff, no cleavage, high crew neckline) and matching wide-leg ribbed lounge pants that flow loosely. Hair in a messy mid bun with face-framing pieces escaping. Soft natural morning light. Vibe: rich morning routine, soft, warm, parasocial.$$
WHERE slug = 'morning_kitchen';

UPDATE content_frameworks SET prompt_template = $$Generate a Lure photo concept where Rhea is walking down a sun-dappled European cobblestone street at dusk in Lisbon or Paris, looking back over her shoulder with an inviting smile, mid-stride, fairy lights and old-world facades in soft focus behind her, full-body framing showing her entire outfit head to ankles. Outfit MUST be a fitted floor-length sundress in WARM TERRACOTTA ORANGE with thin shoulder straps and a square neckline that stops AT the collarbone (NO V-neck, NO cleavage), the dress hugs her hourglass silhouette and the soft fabric flows around her legs as she walks, paired with caramel leather lace-up flats. Hair loose and tousled by the breeze. Tan leather crossbody bag slung diagonally across her body. Vibe: travel envy, golden European sunset, free spirit.$$
WHERE slug = 'vacation_stroll';

UPDATE content_frameworks SET prompt_template = $$Generate a Lure photo concept where Rhea is in a beautifully decorated home for Diwali, standing in front of a long row of lit clay diyas arranged on a marble floor, holding a single lit diya in both hands at chest height, with an intricate marigold-flower garland strung along the wall behind her, full-body framing showing her entire saree drape from head to feet. Outfit MUST be a richly embroidered traditional Indian saree in DEEP CRIMSON RED silk with intricate gold zari border running along the entire pallu and hem, draped properly with the pallu over her left shoulder, paired with a matching short-sleeve gold-embroidered red blouse that has a HIGH BOAT NECKLINE covering the entire chest and neck (NO cleavage, NO deep V), classic full saree drape showing the pleats and floor-length skirt portion. Heavy traditional gold jhumka earrings, a gold maang tikka on her hairline, gold bangles on both wrists, hair half-up with a small fresh white jasmine garland tucked in. Soft glowing diya lights illuminate her face with warm magnetic light. Vibe: cultural, magnetic, every Indian aunty's dream Diwali photo.$$
WHERE slug = 'diwali_saree_glow';

UPDATE content_frameworks SET prompt_template = $$Generate a Lure photo concept where Rhea is leaning against the ornate carved-stone railing of her Bandra apartment balcony at golden hour, looking out at the soft-focus Mumbai skyline then turning her head toward the camera with a soft warm smile, full-body framing showing her entire kurta from neck to ankles. Outfit MUST be a flowing floor-length anarkali kurta in WARM MUSTARD YELLOW silk with delicate block-print floral pattern in white and indigo, three-quarter sleeves, a HIGH ROUND NECK that covers the entire chest and collarbone (no cleavage, no V), tight fitted bodice flowing into a wide pleated skirt that brushes the floor, paired with white embroidered chudidar leggings underneath, and gold-embroidered juttis on her feet. Long jhumka earrings, hair loose with face-framing pieces or in a soft low bun. Vibe: cultural, intellectual, the smart Indian girl who reads books and wears handloom.$$
WHERE slug = 'balcony_kurta_sunset';

UPDATE content_frameworks SET prompt_template = $$Generate a Lure photo concept where Rhea is standing in a heritage palace courtyard in Udaipur with intricate stone carvings and arched doorways behind her, the City Palace lake-facing wall in soft-focus distance, one hand gracefully holding the dupatta of her lehenga, body angled three-quarter to the camera with a magnetic confident smile, full-body framing showing her entire lehenga from head to floor. Outfit MUST be a vibrant traditional Rajasthani lehenga in PEACOCK BLUE silk with intricate silver zardozi mirror-work embroidery on the wide flared floor-length skirt, paired with a fitted long-sleeve choli (blouse) in matching peacock blue with HIGH BOAT NECKLINE covering the entire chest and shoulders (NO cleavage, NO sweetheart, NO deep V), and a gold-zari-bordered cream silk dupatta draped over her head and shoulders. Heavy traditional silver jhumka earrings, a gold maang tikka, silver bangles stacked on both wrists, payal anklets visible. Hair half-up with a real fresh red rose tucked behind her ear. Soft golden afternoon light bouncing off the sandstone walls. Vibe: royal Rajasthani heritage, magazine-cover quality, the definitive Indian heritage scroll-stop.$$
WHERE slug = 'udaipur_palace_lehenga';

UPDATE content_frameworks SET prompt_template = $$Generate a Lure photo concept where Rhea is standing next to a long wooden reading table in a beautiful private wood-paneled library lounge with rich dark mahogany walls and floor-to-ceiling shelves filled with leather-bound hardcover books, brass reading lamps glowing on the table, one hand resting on an open hardcover book on the table, the other hand holding a small porcelain espresso cup, body angled three-quarter to the camera with a soft warm closed smile and direct intelligent eye contact, full-body framing showing her entire outfit head to mid-shin. Outfit MUST be a FULLY BUTTONED collared silk blouse in DEEP CHAMPAGNE GOLD with all six buttons fastened up to the collarbone, the top button done at the throat (NO cleavage, NO V-neck, NO bralette, the silk fabric fully covers the entire chest), long sleeves with delicate French cuffs, paired with a high-waisted fitted floor-length pencil skirt in CHARCOAL GREY wool that hugs her hips and shows her hourglass silhouette, and pointed-toe black leather pumps. Hair loose and wavy. Small pearl studs. Soft warm tungsten light from the brass reading lamp. Vibe: extremely intellectual + magnetic, the IIT girl who reads philosophy and dresses like a Vogue cover.$$
WHERE slug = 'library_silk_blouse';

UPDATE content_frameworks SET prompt_template = $$Generate a Lure photo concept where Rhea is standing at the floor-to-ceiling window of a luxury hotel suite in the morning, holding a small espresso cup at chest height, looking out at the city skyline then turning toward the camera with a soft warm smile, full-body framing showing her entire robe from head to mid-calf. Outfit MUST be a plush belted white luxury hotel terry-cloth robe with the belt firmly tied at her natural waist, the lapels overlapping fully across her chest with NO cleavage visible (the robe is closed properly, fabric covers entire chest from collarbone to belt), the robe hem stopping at mid-calf showing bare lower legs and feet in white luxury hotel slippers. Hair in a messy high bun with face-framing pieces escaping. Soft cool morning daylight from the window plus warm interior lamp. Vibe: luxurious morning ritual, aspirational wealth, soft magnetism, slow morning energy.$$
WHERE slug = 'hotel_robe_morning';

UPDATE content_frameworks SET prompt_template = $$Generate a Lure photo concept where Rhea is standing in a contemporary art gallery exploring an exhibit, mid-stride beside a large abstract canvas painting, looking at the camera with a knowing intelligent smile, full-body framing showing her entire outfit head to ankles. Outfit MUST be a sharply tailored oversized power suit in DEEP CHOCOLATE BROWN with a long single-breasted blazer worn open over a fitted high-neck cream silk shell with a HIGH MOCK-NECK collar covering the entire chest and shoulders (NO cleavage, NO V-neck, NO sweetheart), matching wide-leg high-waisted brown trousers that flow over the foot, and pointed-toe nude leather pumps. Hair loose and wavy with center part. Small gold bar earrings. Soft museum spotlights creating directional light on her face. Vibe: intellectual cultured wealthy, the woman who collects art, modern smart-hot register that signals depth + wealth.$$
WHERE slug = 'art_gallery_blazer_lure';

-- 2. Reload PostgREST schema cache so concept_drafter sees the new templates
NOTIFY pgrst, 'reload schema';

-- 3. Apply explicit GRANTs (in line with sql/027 future-proofing)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE content_frameworks TO authenticated, service_role;
